owner: "duckdb"
repo_name: "duckdb-wasm"
output_dir: "."
root_md_files_output: "root_md_files.jsonl"
license_output: "license.jsonl"
releases_output: "releases.jsonl"
contributors_output: "contributors.jsonl"
commits_output: "commits.jsonl"
issues_output: "issues.jsonl"

# GitHub API configuration
github_api_url: "https://api.github.com/graphql"
pagination_limit: 100
date_range_days: 365
request_timeout: 30
